# Generated by Django 5.2.7 on 2025-10-16 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('pos', 'مثبت'), ('neg', 'منفی'), ('num', 'عدد')], max_length=8, verbose_name='نوع')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='مقدار')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='grades.student')),
            ],
            options={
                'verbose_name': 'ورودی دفتر نمره',
                'verbose_name_plural': 'ورودی\u200cهای دفتر نمره',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
