# Generated by Django 5.2.7 on 2025-10-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_gradebookentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام معلم'),
        ),
        migrations.AlterField(
            model_name='gradebookentry',
            name='entry_type',
            field=models.CharField(choices=[('pos', 'مثبت'), ('neg', 'منفی'), ('num', 'نمره')], max_length=8, verbose_name='نوع'),
        ),
    ]
