# Generated by Django 5.2.7 on 2025-10-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_subject_teacher_name_alter_gradebookentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradebookentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='grades.subject'),
        ),
    ]
