# Generated by Django 5.2.7 on 2025-10-16 10:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_gradebookentry_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره'),
        ),
        migrations.AlterField(
            model_name='gradebookentry',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)], verbose_name='مقدار'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('present', models.BooleanField(default=True, verbose_name='حاضر')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='grades.student')),
            ],
            options={
                'verbose_name': 'حضور/غیاب',
                'verbose_name_plural': 'لیست حضور و غیاب',
                'unique_together': {('student', 'date')},
            },
        ),
    ]
