# Generated by Django 5.2.7 on 2025-10-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_alter_grade_score_alter_gradebookentry_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date_jalali',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ (شمسی)'),
        ),
        migrations.AddField(
            model_name='gradebookentry',
            name='date_jalali',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ (شمسی)'),
        ),
    ]
