# Generated by Django 5.2.7 on 2025-10-17 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_attendance_date_jalali_gradebookentry_date_jalali'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='ایمیل معتبر نیست.')], verbose_name='ایمیل ۱'),
        ),
        migrations.AddField(
            model_name='student',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='ایمیل معتبر نیست.')], verbose_name='ایمیل ۲'),
        ),
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید فقط شامل ارقام باشد (۸ تا ۲۰ رقم).', regex='^\\d{8,20}$')], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن معتبر نیست.', regex='^[+\\d][\\d\\-\\s]{7,}$')], verbose_name='شماره تلفن ۱'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن معتبر نیست.', regex='^[+\\d][\\d\\-\\s]{7,}$')], verbose_name='شماره تلفن ۲'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone3',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن معتبر نیست.', regex='^[+\\d][\\d\\-\\s]{7,}$')], verbose_name='شماره تلفن ۳'),
        ),
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('date_jalali', models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ (شمسی)')),
                ('present', models.BooleanField(default=True, verbose_name='حاضر')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آرشیو')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_history', to='grades.student')),
            ],
            options={
                'verbose_name': 'تاریخچه حضور/غیاب',
                'verbose_name_plural': 'تاریخچه حضور/غیاب',
                'ordering': ['-archived_at', '-date'],
            },
        ),
        migrations.CreateModel(
            name='GradebookEntryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('pos', 'مثبت'), ('neg', 'منفی'), ('num', 'نمره')], max_length=8, verbose_name='نوع')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='مقدار')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ')),
                ('date_jalali', models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ (شمسی)')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آرشیو')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_history', to='grades.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.subject')),
            ],
            options={
                'verbose_name': 'تاریخچه دفتر نمره',
                'verbose_name_plural': 'تاریخچه دفتر نمره',
                'ordering': ['-archived_at', '-date'],
            },
        ),
    ]
