# Generated by Django 5.2.7 on 2025-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_student_email1_student_email2_student_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, help_text='رمز عبور برای ورود دانش\u200cآموز به سیستم', max_length=128, null=True, verbose_name='رمز عبور'),
        ),
    ]
